export const TABLE_ROW_ADD_SUCCESS = 'TABLE_ROW_ADD_SUCCESS';
export const TABLE_ROW_DELETE_SUCCESS = 'TABLE_ROW_DELETE_SUCCESS';
export const TABLE_ROW_EDIT_SUCCESS = 'TABLE_ROW_EDIT_SUCCESS';
export const TABLE_ROW_EDIT_TOGGLE = 'TABLE_ROW_EDIT_SUCCESS';
export const TABLE_CELL_UPDATE = 'TABLE_CELL_UPDATE';
export const TABLE_CELL_TOGGLE = 'TABLE_CELL_TOGGLE';
